services:
  web-dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: yl-flystar-web:dev
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped

  web-prod:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    image: yl-flystar-web:latest
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    restart: unless-stopped
